# Generated by Django 5.2.6 on 2025-09-27 11:29

from django.db import migrations, models


def create_about_panel(apps, schema_editor):
    Panel = apps.get_model("core", "HomeAboutPanel")
    if Panel.objects.exists():
        return
    Panel.objects.create(
        title_emphasis="Toegewijd",
        title_rest="aan kwaliteit en vakmanschap.",
        lead_text="HMD Klusbedrijf is opgericht door Juma Al Huseyin en staat voor betrouwbaarheid, kwaliteit en eerlijke service. Met oog voor detail voert hij elke klus uit alsof het zijn eigen huis is.",
        body_text="Of het nu gaat om kleine reparaties, schilderwerk, timmerklussen of een volledige badkamerrenovatie - HMD Klusbedrijf levert professioneel werk binnen een straal van 50 km rond Dinteloord.",
        cta_label="Lees Meer",
        cta_url="/over-ons/",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_domainname_hosting_overview_seo_socialnetworks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_emphasis', models.CharField(default='Toegewijd', max_length=60)),
                ('title_rest', models.CharField(default='aan kwaliteit en vakmanschap.', max_length=160)),
                ('lead_text', models.TextField(blank=True, default='HMD Klusbedrijf is opgericht door Juma Al Huseyin en staat voor betrouwbaarheid, kwaliteit en eerlijke service. Met oog voor detail voert hij elke klus uit alsof het zijn eigen huis is.')),
                ('body_text', models.TextField(blank=True, default='Of het nu gaat om kleine reparaties, schilderwerk, timmerklussen of een volledige badkamerrenovatie - HMD Klusbedrijf levert professioneel werk binnen een straal van 50 km rond Dinteloord.')),
                ('cta_label', models.CharField(default='Lees Meer', max_length=80)),
                ('cta_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Homepage about panel',
                'verbose_name_plural': 'Homepage about panel',
            },
        ),
        migrations.RunPython(create_about_panel, migrations.RunPython.noop),
    ]

