# Generated by Django 5.2.6 on 2025-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homeaboutpanel_domainname_hosting_overview_seo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutpanel',
            name='cta_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
