# Generated by Django 5.2.6 on 2025-09-27 12:03

from pathlib import Path
from django.conf import settings
from django.core.files import File
from django.db import migrations, models


def seed_carousel(apps, schema_editor):
    Item = apps.get_model("core", "HomeCarouselItem")
    if Item.objects.exists():
        return
    static_root = Path(settings.BASE_DIR) / "static"
    defaults = [
        ("img/gallery/pic8.jpg", "Project in uitvoering"),
        ("img/gallery/pic6.jpg", "Werk in de tuin"),
        ("img/gallery/pic9.jpg", "Binnenafwerking"),
    ]
    for index, (rel_path, alt_text) in enumerate(defaults, start=1):
        file_path = static_root / rel_path
        item = Item(order=index, alt_text=alt_text)
        if file_path.exists():
            with file_path.open('rb') as fh:
                item.image.save(file_path.name, File(fh), save=False)
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_domainname_hosting_overview_seo_socialnetworks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home-carousel/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_carousel, migrations.RunPython.noop),
    ]
