# Generated by Django 5.2.6 on 2025-09-27 12:13

from pathlib import Path
from django.conf import settings
from django.core.files import File
from django.db import migrations, models


def seed_value_block(apps, schema_editor):
    Block = apps.get_model("core", "HomeValueBlock")
    if Block.objects.exists():
        return
    block = Block()
    block.title_emphasis = 'Wij leveren'
    block.title_rest = 'vakwerk waar u op kunt vertrouwen'
    block.body = 'HMD Klusbedrijf voert elke klus met zorg en vakmanschap uit. Of het nu gaat om een kleine reparatie of een complete renovatie, wij staan klaar voor particulieren in de regio Dinteloord en omgeving.'
    block.link_1_label = 'Klus en Reparatiewerk'
    block.link_1_url = '/diensten/kluswerk/'
    block.link_2_label = 'Timmerwerk & interieur'
    block.link_2_url = '/diensten/timmerwerk/'
    block.link_3_label = 'Badkamerrenovatie & buitenwerk'
    block.link_3_url = '/diensten/badkamer-renovatie/'
    image_path = Path(settings.BASE_DIR) / 'static' / 'img' / 'gallery' / 'pic9.jpg'
    if image_path.exists():
        with image_path.open('rb') as fh:
            block.image.save(image_path.name, File(fh), save=False)
    block.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homecarouselitem_domainname_hosting_overview_seo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeValueBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home-value/')),
                ('image_alt', models.CharField(blank=True, default='Werk in uitvoering', max_length=160)),
                ('title_emphasis', models.CharField(default='Wij leveren', max_length=80)),
                ('title_rest', models.CharField(default='vakwerk waar u op kunt vertrouwen', max_length=160)),
                ('body', models.TextField(blank=True, default='HMD Klusbedrijf voert elke klus met zorg en vakmanschap uit. Of het nu gaat om een kleine reparatie of een complete renovatie, wij staan klaar voor particulieren in de regio Dinteloord en omgeving.')),
                ('link_1_label', models.CharField(blank=True, default='Klus en Reparatiewerk', max_length=120)),
                ('link_1_url', models.CharField(blank=True, default='/diensten/kluswerk/', max_length=200)),
                ('link_2_label', models.CharField(blank=True, default='Timmerwerk & interieur', max_length=120)),
                ('link_2_url', models.CharField(blank=True, default='/diensten/timmerwerk/', max_length=200)),
                ('link_3_label', models.CharField(blank=True, default='Badkamerrenovatie & buitenwerk', max_length=120)),
                ('link_3_url', models.CharField(blank=True, default='/diensten/badkamer-renovatie/', max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage value block',
                'verbose_name_plural': 'Homepage value block',
            },
        ),
        migrations.RunPython(seed_value_block, migrations.RunPython.noop),
    ]
