# Generated by Django 5.2.6 on 2025-09-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homevalueblock_domainname_hosting_overview_seo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-carousel/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About carousel item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutCompanyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_number', models.CharField(default='25', max_length=10)),
                ('years_label', models.CharField(default='Jaar Ervaring', max_length=60)),
                ('heading', models.CharField(default='Leefkwaliteit verbeteren met een persoonlijke en vakkundige aanpak.', max_length=160)),
                ('body', models.TextField(blank=True, default='Bij HMD Klusbedrijf draait alles om vakmanschap, betrouwbaarheid en oog voor detail. Al 25 jaar levert oprichter Juma Al Huseyin kwalitatief werk in en rond Dinteloord - van schilderwerk tot volledige renovaties.')),
                ('cta_label', models.CharField(blank=True, default='Neem contact op', max_length=120)),
                ('cta_url', models.CharField(blank=True, default='/contact/', max_length=200)),
            ],
            options={
                'verbose_name': 'About company block',
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wij bouwen aan kwaliteit en sterkere gemeenschappen.', max_length=160)),
                ('background_image', models.ImageField(blank=True, upload_to='about-hero/')),
            ],
            options={
                'verbose_name': 'About hero',
                'verbose_name_plural': 'About hero',
            },
        ),
        migrations.CreateModel(
            name='AboutProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('step_title', models.CharField(default='Stap 1', max_length=60)),
                ('heading', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='about-process/')),
            ],
            options={
                'verbose_name': 'About process step',
                'verbose_name_plural': 'About process steps',
                'ordering': ['order'],
            },
        ),
    ]
