# Generated by Django 5.0.7 on 2025-09-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aboutcarouselitem_aboutcompanyblock_abouthero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="company_name",
            field=models.CharField(max_length=120, blank=True, default="HMD Klusbedrijf"),
        ),
    ]

