# Generated by Django 5.2.6 on 2025-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_company_name_to_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='about-benefits/')),
                ('image_alt', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'About benefit',
                'verbose_name_plural': 'About benefits',
                'ordering': ['order', 'id'],
            },
        ),
    ]
