# Generated by Django 5.0.7 on 2025-10-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutbenefit_domainname_hosting_overview_seo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefoon')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Plaats')),
                ('services', models.TextField(verbose_name='Gewenste Diensten')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Gewenste Datum')),
                ('flexible_timing', models.BooleanField(default=False, verbose_name='Datum Flexibel')),
                ('description', models.TextField(blank=True, verbose_name='Opmerking/Beschrijving')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangevraagd op')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adres')),
                ('user_agent', models.TextField(blank=True, verbose_name='Browser Info')),
                ('status', models.CharField(choices=[('new', 'Nieuw'), ('contacted', 'Contact opgenomen'), ('quoted', 'Offerte verstuurd'), ('accepted', 'Geaccepteerd'), ('completed', 'Voltooid'), ('declined', 'Afgewezen')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Interne notities')),
            ],
            options={
                'verbose_name': 'Offerte Aanvraag',
                'verbose_name_plural': 'Offerte Aanvragen',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
