# Generated by Django 5.0.7 on 2025-10-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutbenefit_domainname_hosting_overview_seo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_display',
            field=models.EmailField(default='info@hmdklusbedrijf.nl', help_text='E-mailadres dat bezoekers zien op de website', verbose_name='Contact E-mail (zichtbaar op website)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_receive',
            field=models.EmailField(default='justcodeworks@gmail.com', help_text='E-mailadres waar contactformulieren naartoe worden gestuurd', verbose_name='E-mail ontvangst'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='+31687111289', help_text='Inclusief landcode (bijvoorbeeld: +31687111289)', max_length=32, verbose_name='WhatsApp Nummer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_address',
            field=models.TextField(blank=True, default='Dinteloord, Nederland', help_text='Volledig adres inclusief postcode en plaats', verbose_name='Bedrijfsadres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kvk_number',
            field=models.CharField(blank=True, default='', help_text='Kamer van Koophandel nummer', max_length=20, verbose_name='KvK Nummer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_times',
            field=models.TextField(blank=True, default='Maandag t/m vrijdag: 8:00 - 17:00\nWeekend: Op afspraak', help_text='Openingstijden en beschikbaarheid', verbose_name='Openingstijden'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Volledige Facebook URL (bijvoorbeeld: https://facebook.com/hmdklusbedrijf)', verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Volledige Instagram URL (bijvoorbeeld: https://instagram.com/hmdklusbedrijf)', verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_display',
            field=models.CharField(blank=True, default='06 87111289', help_text='Hoe het telefoonnummer op de website wordt weergegeven', max_length=32, verbose_name='Telefoonnummer (weergave)'),
        ),
    ]
