# Generated by Django 5.0.7 on 2025-10-05 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('performance', 'Website Performance'), ('seo', 'SEO Recommendations'), ('content', 'Content Suggestions'), ('business', 'Business Opportunities'), ('analytics', 'Analytics Analysis')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('analytics_data', models.JSONField(blank=True, default=dict)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('admin_help', 'Admin Help'), ('business_insights', 'Business Insights'), ('content_generation', 'Content Generation'), ('demo', 'Demo Feature')], max_length=20)),
                ('question', models.TextField()),
                ('ai_response', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
